# Generated by Django 5.2.5 on 2025-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_num', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apt_num', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('dob', models.TextField()),
                ('date_registration', models.TextField()),
                ('precinct', models.IntegerField()),
                ('v20', models.TextField()),
                ('v21', models.TextField()),
                ('v22', models.TextField()),
                ('v23', models.TextField()),
                ('voter_score', models.TextField()),
            ],
        ),
    ]
