# Generated by Django 5.2.5 on 2025-10-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='v21',
        ),
        migrations.AddField(
            model_name='voter',
            name='party',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='apt_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
