# Generated by Django 5.2.5 on 2025-10-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
