# Generated by Django 5.2.5 on 2025-11-23 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_notes_note_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(null=True, blank=True, to='project.profile', on_delete=models.CASCADE),
            preserve_default=False,
        ),
    ]
