# Generated by Django 5.2.5 on 2025-11-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile'),
        ),
    ]
