# Generated by Django 5.2.5 on 2025-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_account_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='card',
            new_name='card_num',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='card_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
