# Generated by Django 5.2.5 on 2025-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_name_account_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
