# Generated by Django 5.2.5 on 2025-11-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.profile'),
            preserve_default=False,
        ),
    ]
